# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15f64a2effe5e7fc24f42298ce864c9f"
name = "WaNotify"
handle = "wanotify"
application_url = "https://type-boring-cardiff-outdoors.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders_create"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks/fulfillments_create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://type-boring-cardiff-outdoors.trycloudflare.com/auth/callback", "https://type-boring-cardiff-outdoors.trycloudflare.com/auth/shopify/callback", "https://type-boring-cardiff-outdoors.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
